### ISSUE TITLE
Instance closure protection

### ISSUE THREAD

**Issue by shellkr** [git-federation/gitpub#10]
I missing a 'Instance closure protection' point. How the protocol should handle stuff on cases where a instance (unexpectedly) shuts down. There is otherwise a great risk many projects, especially inactive, that would likely get lost in such an event. Some kind of archiving would be desirable. 

This would introduce some other complexities. Like how to handle when you want to delete or move a repo.

**Comment by bill-auger** [comment]
most discussion here so far is revolved entirely around the communication protocol and explicitly that is should be extensions to activity-pub - if you are actually thinking what the server implementation might need to do then kudos to you

im not quite sure what you are suggesting; but i guess you are imagining a server that shuts down and leaves it users with no data? - there is no protection for that sort of thing - there does not need to be, and there should not be - in a federated network, each server admin is fully in control of their "home-server" and can turn it off at any time they choose - each user of any network service is 100% responsible for backing up their own data - that should be a commonly known fact by every internet user - if that user no longer wants to publish their code, they do not need to; nor does anyone else need to preserve it - ideally the server admin and the project maintainer are the same person so this is mostly a moot point

the behavior you describe could only be part of the server implementation or some external crawler - it is not something that a protocol spec can or should address - the very nature of federation is that each server is autonomous - any repo can be deleted and any server is free to shut down at any time without warning and it is assumed by all parties that they may do so - there could be a "repo-deleted" message but it would be purely informational - nothing actually needs to happen

does that answer your question? i think this is a non-issue

**Comment by shellkr** [comment]
@bill-auger Why I think about this is because it happened Mastodon twice(?). For one it was an instant shutdown and a couple of thousands users was unable to login to their accounts. If one of the biggest instances did this, it would be a devastating blow and could possible even kill the project. It is one of the biggest weaknesses of federation and a sort of paradox. Either you make and host your own instance or you pick the biggest instance in hopes it will live a long time. 

You are right that GitPub perhaps is not the right place for this... but why I was thinking of GitPub is because it would probably only be forcible trough the protocol. 

Maybe an archive.org kind of bot is the only solution... the issue with such a solution is that it would be really problematic to delete a project. If the protocol handled it.. it could be done reversible throughout the system.

**Comment by bill-auger** [comment]
it is not possible in a federated network to force any node to do anything nor to stop doing something - (do read that sentence again) - all federated nodes are autonomous - that means they and only they decide what to do and when - messages from peers nodes are no more than information upon which the receiver bases it decisions of what to do (or not) - if a server receives a message that says "i (a different server) insist that you delete your repo named 'abc" - the server is just as entitled to ignore as to comply - as well with a message that says "i insist you never power off - you must keep you service running forever" - you could put such messages in the protocol if you like; but every server would probably just ignore them, as they are fully entitled to

it is entirely up to you as the person who is interested in any particular data to backup that data yourself

**Comment by jaywink** [comment]
Regarding instances disappearing from the network, I once wrote this (messy) [draft spec](https://the-federation.info/specs/backup-restore/) with the aim of protecting identities in a federated network. The idea did evolve into actual work for server to server migration in the Diaspora protocol, but that wasn't the main point of my idea. The main point was to allow automatic (encrypted) identity backup on other servers on the network to allow users to restore their identity on another server, in the case of their home server disappearing.

As bill-auger said, there is no way to force someone to run their server forever. The only way is to somehow make the identities available even if the server disappears. And if this isn't an automated process, I would consider it useless for most users. Only a minority of users will remember to backup (or clone) their external service data. I never do for sure :)

Btw, there is good discussion on this topic in the W3C SocialCG [issue tracker](https://github.com/swicg/general/issues/1).
