### ISSUE TITLE
Excercise in uselessnes

### ISSUE THREAD

**Issue by mcepl** [git-federation/gitpub#3]
1. This specification is so liveable, that it is not even hosted inside of any project, which could eventually implement it. https://gitlab.com/gitlab-org/gitlab-ce/issues/4013 shows exactly what is the future of such proposal: nothing, because every repository wants to just lock-in their users.

2. Specification is done: [GIT-REQUEST-PULL(1)](https://linux.die.net/man/1/git-request-pull). Post its output to a comment box (or send it to the agreed-upon email address) and the server would create a pull request automatically and communicate via email with the original committer. Which leads back to the square one: the problem is not specification, but lack of interest on the side of repositories.

**Comment by yookoala** [comment]
1. It is trivial to move the specification to any git service. Besides, hosting it on any specific project could raise question if the specification is bias towards any of them. So, just a matter of point of view.
2. There are multiple software that could potential implement a specification like this. But before a formal specification, any implementation is potential just talking to their own kind. Federation across implementation can raise awareness and interests. And active lobbying and communicating could make such things happen. IMO, ActivityPub has proved it quite clearly.

Thanks for your opinion anyway.

**Comment by mcepl** [comment]
Sorry, this is really not productive. Sorry, for bothering you, and good luck with your effort (although I don'ŧ believe in it, I heartily wish you would succeed).

**Comment by aep** [comment]
There's usefull feedback embedded into this rant.
Why do you think there's a lack of interest and what could change that?

**Comment by mcepl** [comment]
> Why do you think there's a lack of interest and what could change that?

"… every repository wants to just lock-in their users" ?

But may point is that implementation of something trivial which would work (and show usefulness of distributed development) would be trivial, if there was a will on the side of the repo gatekeepers. The fact, that nothing happened shows to me clearly, that there is no will.

To be honest, there is possibly [something](https://gitlab.com/gitlab-org/gitlab-ce/issues/32878) in [Gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/40830), but I was not able to decipher how it is supposed to work, and whether it is enabled on gitlab.com.
