### ISSUE TITLE
Add @techknowlogick to Working Group

### ISSUE THREAD

**Issue by techknowlogick** [git-federation/gitpub#4]
Hi,

I'm @techknowlogick, a contributor and one of several maintainers of Gitea. Please check https://github.com/go-gitea/gitea/blob/master/MAINTAINERS for verification. While I can't speak on behalf of the project, federation is a topic that I am personally interested in and would like to be a part of the conversation.

Thanks,
@techknowlogick

**Comment by yookoala** [comment]
@techknowlogick Thanks for the input. As suggested by others, we may need a more formal discussion than using github issues. Please join our discussion in #5 and we'll decide how we should run the discussion. Thanks.

**Comment by yookoala** [comment]
I have added the email stated in your Github profile to the work group mailing list. If not, please send me a email through the address stated in [this comment on #5](https://github.com/git-federation/gitpub/issues/5#issuecomment-395283212). Thanks.
